#The things that I left in the config are supposed to demonstrate how it should work and look.
#Remove my stuff and put your stuff here. 

# Shared settings
TEMPLATE_VMID=198
#STORAGE="local-lvm"

# Where scripts are stored inside Windows
GUEST_SCRIPT_DIR="C:\\automation"

# Number of clones
CLONE_COUNT=5

# -------- Clone 1 --------
CLONE_NAME[1]="host1"

CLONE_SCRIPTS[1]="
host1script0.ps1|YourDirectCloudStorageLinkToScript
host1script1.ps1|YourDirectCloudStorageLinkToScript
host1script2.ps1|YourDirectCloudStorageLinkToScript
host1finalreboot.ps1|YourDirectCloudStorageLinkToScript
"

# -------- Clone 2 --------
CLONE_NAME[2]="host2"

CLONE_SCRIPTS[2]="
host2script0.ps1|YourDirectCloudStorageLinkToScript
host2script1.ps1|YourDirectCloudStorageLinkToScript
host2script2.ps1|YourDirectCloudStorageLinkToScript
host2finalreboot.ps1|YourDirectCloudStorageLinkToScript
"

# -------- Clone 3 --------
CLONE_NAME[3]="host3"

CLONE_SCRIPTS[3]="
host3script0.ps1|YourDirectCloudStorageLinkToScript
host3script1.ps1|YourDirectCloudStorageLinkToScript
host3script2.ps1|YourDirectCloudStorageLinkToScript
host3finalreboot.ps1|YourDirectCloudStorageLinkToScript
"

# -------- Clone 4 --------
CLONE_NAME[4]="broker"

CLONE_SCRIPTS[4]="
brokerscript0.ps1|YourDirectCloudStorageLinkToScript
brokerscript1.ps1|YourDirectCloudStorageLinkToScript
brokerscript2.ps1|YourDirectCloudStorageLinkToScript
prebrokerscript3Areboot.ps1|YourDirectCloudStorageLinkToScript
brokerscript3A.ps1|YourDirectCloudStorageLinkToScript
brokerscript3B.ps1|YourDirectCloudStorageLinkToScript
brokerfinalreboot.ps1|YourDirectCloudStorageLinkToScript
"

# -------- Clone 5 --------
CLONE_NAME[5]="client"

CLONE_SCRIPTS[5]="
client1script0.ps1|YourDirectCloudStorageLinkToScript
client1script1.ps1|YourDirectCloudStorageLinkToScript
client1script2.ps1|YourDirectCloudStorageLinkToScript
"